menu:
  buttons:
    - text: "Choose"
    - text: "Edit"
yes_no:
  one_time_keyboard: on
  buttons:
    - text: "Yes"
    -
    - text: "No"
items:
  buttons:
    - text: "remove"
      callback_data: "remove_kb"
    -
    - text: "Buy apple"
      callback_data:
        name: "Apple"
        cost: 123
    - text: "Buy banana"
      callback_data:
        name: "Banana"
        cost: 456
